# conda env create -f environment.yml
name: mmSNN
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - snntorch
  - pip
  - pip:
    - tonic
    - torchdata
